[package]
name = "lousy_project_name"
version = "0.2.0"
authors = ["Tim Warrington <tim.warrin@gmail.com>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2.33"
rand = { version = "0.6.4", features = ["wasm-bindgen"] }

[lib]
crate-type = ["cdylib"]
